import { z } from "zod";

export const createTaskSchema = z.object({
  title: z.string().min(1, "Title is required").max(255),
  description: z.string().optional(),
  type: z.string().default("feature"),
  status: z.string().default("todo"),
  priority: z.string().default("medium"),
  projectId: z.string().uuid().nullable().optional(),
  courseId: z.string().uuid().nullable().optional(),
  sprintId: z.string().uuid().nullable().optional(),
  storyPoints: z.string().nullable().optional(),
  estimatedMinutes: z.number().int().nonnegative().nullable().optional(),
  actualMinutes: z.number().int().nonnegative().default(0),
  startDate: z.string().datetime().nullable().optional(),
  dueDate: z.string().datetime().nullable().optional(),
  academicWeight: z.string().nullable().optional(),
  githubIssueUrl: z.string().url().nullable().optional().or(z.literal("")),
  githubPrUrl: z.string().url().nullable().optional().or(z.literal("")),
  branchName: z.string().nullable().optional(),
  labelIds: z.array(z.string().uuid()).optional(),
});

export const updateTaskSchema = z.object({
  id: z.string().uuid(),
  title: z.string().min(1).max(255).optional(),
  description: z.string().nullable().optional(),
  type: z.string().optional(),
  status: z.string().optional(),
  priority: z.string().optional(),
  projectId: z.string().uuid().nullable().optional(),
  courseId: z.string().uuid().nullable().optional(),
  sprintId: z.string().uuid().nullable().optional(),
  storyPoints: z.string().nullable().optional(),
  estimatedMinutes: z.number().int().nonnegative().nullable().optional(),
  actualMinutes: z.number().int().nonnegative().optional(),
  startDate: z.string().datetime().nullable().optional(),
  dueDate: z.string().datetime().nullable().optional(),
  academicWeight: z.string().nullable().optional(),
  githubIssueUrl: z.string().nullable().optional(),
  githubPrUrl: z.string().nullable().optional(),
  branchName: z.string().nullable().optional(),
  expectedVersion: z.number().int().positive().optional(),
});
